In [2]:
# x = [[1, 1, 1, 0, 0, 0] [0, 1, 0, 0, 0, 0 ], [1, 1, 1, 0, 0, 0], [0, 0, 2, 4, 4, 0], [0, 0, 0, 2, 0, 0], [0, 0, 0, 2, 0, 0], [0, 0, 1, 2, 4, 0]]

TypeError: list indices must be integers or slices, not tuple

In [ ]:
def hourglassSum(x):
    maxhg_x = 0
    
    
    for i in range(0,x.shape[0] - 2):
        for j in range(0, x.shape[1] - 2):
            hg_x = ((x[i][j] + x[i][j+1] + x[i][j+2]) + (x[i+1][j+1]) + (x[i][j+2] + x[i+1][j+2] + x[i+2][j+2]) )

    
            
            
            
    if hg_x > maxhg_x:
        maxhg_x = hg_x
        
        
    #return hg_x       
    return (x[i][j] , x[i][j+1] , x[i][j+2]) , (x[i+1][j+1]) , (x[i+2][j] , x[i+2][j+1] , x[i+2][j+2])

In [57]:
import numpy as np 
np.random.random((3, 3))

array([[0.32738588, 0.2502985 , 0.00665016],
       [0.28564849, 0.86039902, 0.84882171],
       [0.6948905 , 0.70055557, 0.49426812]])

In [58]:
x= np.random.randint(-9,9, size=(6,6))

In [59]:
print(x)

[[ 5  6 -7  2  6  6]
 [-2 -7 -2  4 -2 -2]
 [ 0 -2 -8 -8  0  2]
 [ 3 -6 -4  0  2  5]
 [ 3 -7  4  5  2  5]
 [-5  2  8 -4 -5 -5]]


In [60]:
x[0]

array([ 5,  6, -7,  2,  6,  6])

In [61]:
x[0][0]

5

In [62]:
len(x)

6

In [63]:
x.shape

(6, 6)

In [64]:
x.shape[0]

6

In [65]:
def hourglassSum(x):
    maxhg_x = 0
    
    
    for i in range(0,x.shape[0] - 2):
        for j in range(0, x.shape[1] - 2):
            hg_x = ((x[i][j] + x[i][j+1] + x[i][j+2]) + (x[i+1][j+1]) + (x[i][j+2] + x[i+1][j+2] + x[i+2][j+2]) )
            
            
            
            if hg_x > maxhg_x:
                maxhg_x = hg_x
        
        
    #return hg_x       
    return (x[i][j] , x[i][j+1] , x[i][j+2]) , (x[i+1][j+1]) , (x[i][j+2] , x[i+1][j+2] , x[i+2][j+2])

In [66]:
hourglassSum(x)

((0, 2, 5), 2, (5, 5, -5))

In [141]:
def hourglassSum(x):
    
    i = 0
    j = 0
    
    maxhg_x = (x[i][j] + x[i][j+1] + x[i][j+2] + x[i+1][j+1] + x[i][j+2] + x[i+1][j+2] + x[i+2][j+2] )
    
    
    for i in range(0,4):
        for j in range(0, 4):
            hg_x = (x[i][j] + x[i][j+1] + x[i][j+2] + x[i+1][j+1] + x[i+2][j] + x[i+2][j+1] + x[i+2][j+2] )
            if hg_x > maxhg_x:
                maxhg_x = hg_x

            

        
        
    return maxhg_x       
    #return (x[i][j] , x[i][j+1] , x[i][j+2]) , (x[i+1][j+1]) , (x[i+2][j] , x[i+2][j+1] , x[i+2][j+2])

In [142]:
x

array([[ 5,  6, -7,  2,  6,  6],
       [-2, -7, -2,  4, -2, -2],
       [ 0, -2, -8, -8,  0,  2],
       [ 3, -6, -4,  0,  2,  5],
       [ 3, -7,  4,  5,  2,  5],
       [-5,  2,  8, -4, -5, -5]])

In [143]:
(x[i][j] , x[i][j+1] , x[i][j+2]) , (x[i+1][j+1]) , (x[i+2][j] , x[i+2][j+1] , x[i+2][j+2])

((5, 6, -7), -7, (0, -2, -8))

In [144]:
hourglassSum(x)

8

In [145]:
i = 0
j = 0

x[i][j] + x[i][j+1] + x[i][j+2] + x[i+1][j+1] + x[i][j+2] + x[i+1][j+2] + x[i+2][j+2]

-20

In [146]:
(x[i][j] , x[i][j+1] , x[i][j+2]) , (x[i+1][j+1]) , (x[i+2][j] , x[i+2][j+1] , x[i+2][j+2])

((5, 6, -7), -7, (0, -2, -8))

In [147]:
2 < 3 < 4

True