Calculate the maximum value of menu items that can be consumed within the constaint of N calories

Sample I/P: Menu = {'wine', 'beer'}
Calories = {123,154}
Values = {89, 90}
N = 750
Sample O/P - {Total value of items taken =353 given 750 calories
cola: <79,150> pizza: <95,258>} ...

In [22]:
import time
import csv
MAX_CALORIES = 2000

class Food(object):
    def __init__(self, n, v, w):
        self.name = n
        self.value = v
        self.calories = w
    def getValue(self):
        return self.value
    def getCost(self):
        return self.calories
    def density(self):
        return self.getValue()/self.getCost()
    def __str__(self):
        return self.name + ': <' + str(self.value)\
                 + ', ' + str(self.calories) + '>'

def buildMenu(names, values, calories):
    menu = []
    for i in range(len(values)):
        menu.append(Food(names[i], values[i],
                          calories[i]))
    return menu

def testMaxVal(foods, maxUnits, printItems = True):
    print('Allocate', maxUnits, 'calories')
    tic = time.time()
    val, taken = maxVal(foods, maxUnits)
    toc = time.time() - tic
    print('Total value of items taken =', val)
    if printItems:
        for item in taken:
            print('   ', item)
    print("time: %.5fs" % (toc))

def buildMenuFromCSV():
    menu = []
    with open('menu.csv', newline='') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=',')
        for row in spamreader:
            try:
                menu.append(Food(row[0], int(row[1]),
                                int(row[2])))
            except:
                continue
        return menu


def run():
    #example
    names = ['wine', 'beer', 'pizza', 'burger', 'fries',
            'cola', 'apple', 'donut', 'cake']
    values = [89,90,95,100,90,79,50,10]
    calories = [123,154,258,354,365,150,95,195]
    foods = buildMenu(names, values, calories)
    testMaxVal(foods, 750)

    #challenge
    menu = buildMenuFromCSV()
    testMaxVal(menu, MAX_CALORIES)


def maxVal(toConsider, avail):
    """Assumes toConsider is a list of Food, avail a weight (number of calories)
       Returns a tuple of the total value of a solution to the problem
       and a list of Food that comprise the solution"""

    ##################
    # YOUR CODE HERE #
    ##################
    newlist = sorted(toConsider, key=lambda x: x.density(), reverse=True)
    used = 0
    value = 0
    foodlist = []
    for food in newlist:
        print(food, "density:", food.density())
        if food.calories + used <= avail:
            value = value + food.getValue()
            used = used + food.calories
            foodlist.append(food)
    print(f"{used = }")
    return (value, foodlist)

if __name__ == '__main__':
    run()


Allocate 750 calories
wine: <89, 123> density: 0.7235772357723578
beer: <90, 154> density: 0.5844155844155844
cola: <79, 150> density: 0.5266666666666666
apple: <50, 95> density: 0.5263157894736842
pizza: <95, 258> density: 0.3682170542635659
burger: <100, 354> density: 0.2824858757062147
fries: <90, 365> density: 0.2465753424657534
donut: <10, 195> density: 0.05128205128205128
used = 717
Total value of items taken = 318
    wine: <89, 123>
    beer: <90, 154>
    cola: <79, 150>
    apple: <50, 95>
    donut: <10, 195>
time: 0.00164s
Allocate 2000 calories
cookies: <21, 5> density: 4.2
alfredo sauce: <17, 5> density: 3.4
kiwi: <58, 28> density: 2.0714285714285716
eggs: <47, 33> density: 1.4242424242424243
doritos: <83, 61> density: 1.360655737704918
bread: <36, 32> density: 1.125
turkey: <87, 87> density: 1.0
apple pie: <50, 53> density: 0.9433962264150944
tomato: <65, 80> density: 0.8125
marinara sauce: <46, 62> density: 0.7419354838709677
burritos: <53, 96> density: 0.55208333333333

In [ ]:
16

16

In [9]:
36

36

In [15]:
x = 5

In [17]:
print(f"{x = }")

x = 5


Calculate the maximum value of menu items that can be consumed within the constaint of N calories

Sample I/P: Menu = {'wine', 'beer'}
Calories = {123,154}
Values = {89, 90}
N = 750
Sample O/P - {Total value of items taken =353 given 750 calories
cola: <79,150> pizza: <95,258>} ...

In [20]:
def buildMenuFromCSV():
    menu = []
    with open('menu.csv', newline='') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=',')
        for row in spamreader:
            try:
                menu.append(Food(row[0], int(row[1]),
                                int(row[2])))
            except:
                continue
        return menu
menu = buildMenuFromCSV()

In [23]:
def max_knap():
    return 6

In [27]:
# Sort menu in ascending calorie
def buildMenuFromCSV():
    menu = []
    with open('menu.csv', newline='') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=',')
        for row in spamreader:
            try:
                menu.append(Food(row[0], int(row[1]),
                                int(row[2])))
            except:
                continue
        return menu
menu = buildMenuFromCSV()

def maxVal(toConsider, avail):
    newlist = sorted(toConsider, key=lambda x: x.density(), reverse=True)
    return newlist
maxVal(toConsider=menu, avail=750)

In [47]:
import time
import csv
import numpy as np
MAX_CALORIES = 2000

class Food(object):
    def __init__(self, n, v, w):
        self.name = n
        self.value = v
        self.calories = w
    def getValue(self):
        return self.value
    def getCost(self):
        return self.calories
    def density(self):
        return self.getValue()/self.getCost()
    def __str__(self):
        return self.name + ': <' + str(self.value)\
                 + ', ' + str(self.calories) + '>'

def buildMenu(names, values, calories):
    menu = []
    for i in range(len(values)):
        menu.append(Food(names[i], values[i],
                          calories[i]))
    return menu

def testMaxVal(foods, maxUnits, printItems = True):
    print('Allocate', maxUnits, 'calories')
    tic = time.time()
    val, taken = maxVal(foods, maxUnits)
    toc = time.time() - tic
    print('Total value of items taken =', val)
    if printItems:
        for item in taken:
            print('   ', item)
    print("time: %.5fs" % (toc))

def buildMenuFromCSV():
    menu = []
    with open('menu.csv', newline='') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=',')
        for row in spamreader:
            try:
                menu.append(Food(row[0], int(row[1]),
                                int(row[2])))
            except:
                continue
        return menu


def run():
    #example
    names = ['wine', 'beer', 'pizza', 'burger', 'fries',
            'cola', 'apple', 'donut', 'cake']
    values = [89,90,95,100,90,79,50,10]
    calories = [123,154,258,354,365,150,95,195]
    foods = buildMenu(names, values, calories)
    testMaxVal(foods, 750)

    #challenge
    menu = buildMenuFromCSV()
    testMaxVal(menu, MAX_CALORIES)


def maxVal(toConsider, avail):
    """Assumes toConsider is a list of Food, avail a weight (number of calories)
       Returns a tuple of the total value of a solution to the problem
       and a list of Food that comprise the solution"""

    ##################
    # YOUR CODE HERE #
    ##################
    newlist = sorted(toConsider, key=lambda x: x.getCost(), reverse=False)
    # print(f'{newlist = }')
    newlist = newlist[0:5]
    used = 0
    value = 0
    foodlist = []
    n = len(newlist)
    y = n + 1
    x = 10
    step = avail / x

    A = np.zeros((y, x+1), dtype=int)
    # for i in range(1,x+1):
    #     A[0,i] = step * i
    

    j = 1
    for i in range(1,x+1):
        A[j,i] = i+j
    print(A)



    
    
    print(f"{used = }")
    return (value, foodlist)

if __name__ == '__main__':
    run()


Allocate 750 calories
[[ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  3  4  5  6  7  8  9 10 11]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
used = 0
Total value of items taken = 0
time: 0.00029s
Allocate 2000 calories
[[ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  3  4  5  6  7  8  9 10 11]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
used = 0
Total value of items taken = 0
time: 0.00049s


In [71]:
import time
import csv
import numpy as np
MAX_CALORIES = 2000

class Food(object):
    def __init__(self, n, v, w):
        self.name = n
        self.value = v
        self.calories = w
    def getValue(self):
        return self.value
    def getCost(self):
        return self.calories
    def density(self):
        return self.getValue()/self.getCost()
    def __str__(self):
        return self.name + ': <' + str(self.value)\
                 + ', ' + str(self.calories) + '>'

def buildMenu(names, values, calories):
    menu = []
    for i in range(len(values)):
        menu.append(Food(names[i], values[i],
                          calories[i]))
    return menu

def testMaxVal(foods, maxUnits, printItems = True):
    print('Allocate', maxUnits, 'calories')
    tic = time.time()
    val, taken = maxVal(foods, maxUnits)
    toc = time.time() - tic
    print('Total value of items taken =', val)
    if printItems:
        for item in taken:
            print('   ', item)
    print("time: %.5fs" % (toc))

def buildMenuFromCSV():
    menu = []
    with open('menu.csv', newline='') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=',')
        for row in spamreader:
            try:
                menu.append(Food(row[0], int(row[1]),
                                int(row[2])))
            except:
                continue
        return menu


def run():
    #example
    names = ['wine', 'beer', 'pizza', 'burger', 'fries',
            'cola', 'apple', 'donut', 'cake']
    values = [89,90,95,100,90,79,50,10]
    calories = [123,154,258,354,365,150,95,195]
    foods = buildMenu(names, values, calories)
    testMaxVal(foods, 750)

    #challenge
    menu = buildMenuFromCSV()
    testMaxVal(menu, MAX_CALORIES)


def maxVal(toConsider, avail):
    """Assumes toConsider is a list of Food, avail a weight (number of calories)
       Returns a tuple of the total value of a solution to the problem
       and a list of Food that comprise the solution"""

    ##################
    # YOUR CODE HERE #
    ##################
    newlist = sorted(toConsider, key=lambda x: x.getCost(), reverse=False)
    # print(f'{newlist = }')
    newlist = newlist[0:5]
    used = 0
    value = 0
    foodlist = []
    n = len(newlist)
    y = n + 1
    x = avail
    step = avail / x

    A = np.zeros((y, x+1), dtype=int)
    # for i in range(1,x+1):
    #     A[0,i] = step * i
    

    j = 1
    x_step = newlist[j].getCost()
    current_value = newlist[j].getValue()
    for i in range(1,x+1, x_step):
        # A[j,i] = i+j
        if i > x_step:
            A[j,i:i+x_step] = current_value
        # print(newlist[j].getCost())
    # print(A[:, ::50])
    print(A[:, 1::x_step])
    # print(A)




    
    
    print(f"{used = }")
    return (value, foodlist)

if __name__ == '__main__':
    run()


Allocate 750 calories
[[ 0  0  0  0  0  0  0]
 [ 0 89 89 89 89 89 89]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]]
used = 0
Total value of items taken = 0
time: 0.00034s
Allocate 2000 calories
[[ 0  0  0 ...  0  0  0]
 [ 0 21 21 ... 21 21 21]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
used = 0
Total value of items taken = 0
time: 0.00046s


In [69]:
test = np.zeros((3,3), dtype=int)
print(test)
test[1,0:2] = 1
print(test)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [1 1 0]
 [0 0 0]]


In [82]:
import time
import csv
import numpy as np
MAX_CALORIES = 2000

class Food(object):
    def __init__(self, n, v, w):
        self.name = n
        self.value = v
        self.calories = w
    def getValue(self):
        return self.value
    def getCost(self):
        return self.calories
    def density(self):
        return self.getValue()/self.getCost()
    def __str__(self):
        return self.name + ': <' + str(self.value)\
                 + ', ' + str(self.calories) + '>'

def buildMenu(names, values, calories):
    menu = []
    for i in range(len(values)):
        menu.append(Food(names[i], values[i],
                          calories[i]))
    return menu

def testMaxVal(foods, maxUnits, printItems = True):
    print('Allocate', maxUnits, 'calories')
    tic = time.time()
    val, taken = maxVal(foods, maxUnits)
    toc = time.time() - tic
    print('Total value of items taken =', val)
    if printItems:
        for item in taken:
            print('   ', item)
    print("time: %.5fs" % (toc))

def buildMenuFromCSV():
    menu = []
    with open('menu.csv', newline='') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=',')
        for row in spamreader:
            try:
                menu.append(Food(row[0], int(row[1]),
                                int(row[2])))
            except:
                continue
        return menu


def run():
    #example
    names = ['wine', 'beer', 'pizza', 'burger', 'fries',
            'cola', 'apple', 'donut', 'cake']
    values = [89,90,95,100,90,79,50,10]
    calories = [123,154,258,354,365,150,95,195]
    foods = buildMenu(names, values, calories)
    testMaxVal(foods, 750)

    #challenge
    menu = buildMenuFromCSV()
    testMaxVal(menu, MAX_CALORIES)


def maxVal(toConsider, avail):
    """Assumes toConsider is a list of Food, avail a weight (number of calories)
       Returns a tuple of the total value of a solution to the problem
       and a list of Food that comprise the solution"""

    ##################
    # YOUR CODE HERE #
    ##################
    newlist = sorted(toConsider, key=lambda x: x.getCost(), reverse=False)
    # print(f'{newlist = }')
    newlist = newlist[0:5]
    used = 0
    value = 0
    foodlist = []
    n = len(newlist)
    y = n + 1
    x = avail
    step = avail / x

    A = np.zeros((y, x+1), dtype=int)
    # for i in range(1,x+1):
    #     A[0,i] = step * i
    

    # j = 1
    for j in range(1,n):
        print(newlist[j])
        x_step = newlist[j].getCost()
        current_value = newlist[j].getValue()
        for i in range(1,x+1, x_step):
            # A[j,i] = i+j
            if i > x_step:
                # grab the max of the column indexed before 
                A[j:y,i:i+x_step] = current_value
                # A[j,i:i+x_step] = max((), ()))

            # print(newlist[j].getCost())
        # print(A[:, ::50])
        # print(A[:, 1::x_step])
        print(A)




    
    
    print(f"{used = }")
    return (value, foodlist)

if __name__ == '__main__':
    run()


Allocate 750 calories
wine: <89, 123>
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ... 89 89 89]
 [ 0  0  0 ... 89 89 89]
 [ 0  0  0 ... 89 89 89]
 [ 0  0  0 ... 89 89 89]
 [ 0  0  0 ... 89 89 89]]
cola: <79, 150>
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ... 89 89 89]
 [ 0  0  0 ... 79 79 79]
 [ 0  0  0 ... 79 79 79]
 [ 0  0  0 ... 79 79 79]
 [ 0  0  0 ... 79 79 79]]
beer: <90, 154>
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ... 89 89 89]
 [ 0  0  0 ... 79 79 79]
 [ 0  0  0 ... 90 90 90]
 [ 0  0  0 ... 90 90 90]
 [ 0  0  0 ... 90 90 90]]
donut: <10, 195>
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ... 89 89 89]
 [ 0  0  0 ... 79 79 79]
 [ 0  0  0 ... 90 90 90]
 [ 0  0  0 ... 10 10 10]
 [ 0  0  0 ... 10 10 10]]
used = 0
Total value of items taken = 0
time: 0.00091s
Allocate 2000 calories
cookies: <21, 5>
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ... 21 21 21]
 [ 0  0  0 ... 21 21 21]
 [ 0  0  0 ... 21 21 21]
 [ 0  0  0 ... 21 21 21]
 [ 0  0  0 ... 21 21 21]]
kiwi: <58, 28>
[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ... 21 21 21

In [112]:
import time
import csv
import numpy as np
import math
MAX_CALORIES = 2000

class Food(object):
    def __init__(self, n, v, w):
        self.name = n
        self.value = v
        self.calories = w
    def getValue(self):
        return self.value
    def getCost(self):
        return self.calories
    def density(self):
        return self.getValue()/self.getCost()
    def __str__(self):
        return self.name + ': <' + str(self.value)\
                 + ', ' + str(self.calories) + '>'

def buildMenu(names, values, calories):
    menu = []
    for i in range(len(values)):
        menu.append(Food(names[i], values[i],
                          calories[i]))
    return menu

def testMaxVal(foods, maxUnits, printItems = True):
    print('Allocate', maxUnits, 'calories')
    tic = time.time()
    val, taken = maxVal(foods, maxUnits)
    toc = time.time() - tic
    print('Total value of items taken =', val)
    if printItems:
        for item in taken:
            print('   ', item)
    print("time: %.5fs" % (toc))

def buildMenuFromCSV():
    menu = []
    with open('menu.csv', newline='') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=',')
        for row in spamreader:
            try:
                menu.append(Food(row[0], int(row[1]),
                                int(row[2])))
            except:
                continue
        return menu


def run():
    #example
    names = ['wine', 'beer', 'pizza', 'burger', 'fries',
            'cola', 'apple', 'donut', 'cake']
    values = [89,90,95,100,90,79,50,10]
    calories = [123,154,258,354,365,150,95,195]
    foods = buildMenu(names, values, calories)
    testMaxVal(foods, 750)

    #challenge
    menu = buildMenuFromCSV()
    testMaxVal(menu, MAX_CALORIES)


def maxVal(toConsider, avail):
    """Assumes toConsider is a list of Food, avail a weight (number of calories)
       Returns a tuple of the total value of a solution to the problem
       and a list of Food that comprise the solution"""

    ##################
    # YOUR CODE HERE #
    ##################
    newlist = sorted(toConsider, key=lambda x: x.getCost(), reverse=False)
    # print(f'{newlist = }')
    newlist = newlist[0:5]
    used = 0
    value = 0
    foodlist = []
    n = len(newlist)
    y = n + 1
    x = avail
    step = avail / x

    A = np.zeros((y, x+1), dtype=int)
    # for i in range(1,x+1):
    #     A[0,i] = step * i
    

    # j = 1
    for j in range(1,n):
        print(newlist[j])
        x_step = newlist[j].getCost()
        current_value = newlist[j].getValue()
        ate = True
        
        for i in range(1,x+1, x_step):
            # A[j,i] = i+j

            if i >= x_step:
                # grab the max of the column indexed before 
                # A[j:y,i:i+x_step] = current_value
                A[j:y,i:i+x_step] = max((A[j,i-x_step] + current_value*ate), (A[j-1,i]))
                print(f"{math.floor(i/x_step) == 1}")
                print(f"{current_value*ate =}")
                if (math.floor(i/x_step) == 1):
                    ate = False

            # print(newlist[j].getCost())
        print(A[:, ::50])
        # print(A[:, 1::x_step])
        # print(A[:,123:180:5])




    
    
    print(f"{used = }")
    return (value, foodlist)

if __name__ == '__main__':
    run()


Allocate 750 calories
wine: <89, 123>
True
current_value*ate =89
False
current_value*ate =0
False
current_value*ate =0
False
current_value*ate =0
False
current_value*ate =0
False
current_value*ate =0
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 89 89 89 89 89 89 89 89 89 89 89 89 89]
 [ 0  0  0 89 89 89 89 89 89 89 89 89 89 89 89 89]
 [ 0  0  0 89 89 89 89 89 89 89 89 89 89 89 89 89]
 [ 0  0  0 89 89 89 89 89 89 89 89 89 89 89 89 89]
 [ 0  0  0 89 89 89 89 89 89 89 89 89 89 89 89 89]]
cola: <79, 150>
True
current_value*ate =79
False
current_value*ate =0
False
current_value*ate =0
False
current_value*ate =0
[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 89 89 89 89 89 89 89 89 89 89 89 89 89]
 [ 0  0  0 89 89 89 89 89 89 89 89 89 89 89 89 89]
 [ 0  0  0 89 89 89 89 89 89 89 89 89 89 89 89 89]
 [ 0  0  0 89 89 89 89 89 89 89 89 89 89 89 89 89]
 [ 0  0  0 89 89 89 89 89 89 89 89 89 89 89 89 89]]
beer: <90, 154>
True
current_value*ate =90
False
current_value

In [99]:
!False * 5